/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
        TestCases tests = new TestCases(); // Initialize your test class

        tests.testCase01();
        tests.testCase02();
        tests.testCase03();
        tests.testCase04();
        tests.testCase05();
        tests.testCase06();
        tests.testCase07();

    }

    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
